/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-primary-fixed": "#201c00",
              "surface-container-low": "#f4f4f0",
              "surface-container-lowest": "#ffffff",
              "error-container": "#ffdad6",
              "on-tertiary": "#ffffff",
              "surface-container": "#eeeeea",
              "on-tertiary-fixed-variant": "#354e00",
              "on-tertiary-fixed": "#131f00",
              "surface-container-high": "#e8e8e4",
              "background": "#faf9f5",
              "tertiary-container": "#b1fa00",
              "surface-dim": "#dadad6",
              "error": "#ba1a1a",
              "on-error": "#ffffff",
              "inverse-primary": "#dec800",
              "tertiary": "#486800",
              "on-primary-fixed-variant": "#504700",
              "on-tertiary-container": "#4d7000",
              "on-primary-container": "#726600",
              "on-background": "#1a1c1a",
              "inverse-surface": "#2f312e",
              "primary-fixed": "#fde400",
              "surface-container-highest": "#e2e3df",
              "on-secondary-fixed": "#002022",
              "primary-fixed-dim": "#dec800",
              "surface-tint": "#6a5f00",
              "on-secondary": "#ffffff",
              "primary-container": "#ffe600",
              "secondary": "#006970",
              "surface-variant": "#e2e3df",
              "on-secondary-container": "#00686f",
              "primary": "#6a5f00",
              "outline-variant": "#cdc7aa",
              "on-secondary-fixed-variant": "#004f54",
              "on-error-container": "#93000a",
              "outline": "#7c775f",
              "secondary-fixed": "#7df4ff",
              "surface-bright": "#faf9f5",
              "on-surface-variant": "#4b4731",
              "secondary-fixed-dim": "#00dbe9",
              "tertiary-fixed": "#b0f800",
              "on-surface": "#1a1c1a",
              "surface": "#faf9f5",
              "on-primary": "#ffffff",
              "secondary-container": "#00eefc",
              "inverse-on-surface": "#f1f1ed",
              "tertiary-fixed-dim": "#9ad900"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-desktop": "64px",
              "gutter": "32px",
              "margin-mobile": "24px",
              "base": "4px",
              "border-width": "4px",
              "section-gap": "128px",
              "shadow-offset": "8px"
      },
      "fontFamily": {
              "body-lg": ["Lexend"],
              "label-bold": ["Space Grotesk"],
              "headline-lg": ["Space Grotesk"],
              "headline-md": ["Space Grotesk"],
              "body-md": ["Lexend"],
              "headline-lg-mobile": ["Space Grotesk"],
              "display": ["Space Grotesk"]
      },
      "fontSize": {
              "body-lg": ["20px", {"lineHeight": "32px", "fontWeight": "400"}],
              "label-bold": ["14px", {"lineHeight": "16px", "fontWeight": "700"}],
              "headline-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg-mobile": ["40px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "display": ["120px", {"lineHeight": "110px", "letterSpacing": "-0.04em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
